-- Tabela para guardar o histórico de cada sessão de estudo
create table public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null, -- Para saber de qual aluno é a sessão
  created_at timestamptz default now(), -- Data e Hora
  duration int8 not null, -- Tempo em minutos
  type text not null -- 'FOCUS' (Estudo) ou 'BREAK' (Pausa)
);

-- Desativa segurança para facilitar o desenvolvimento (Fase de Estudo)
alter table public.study_sessions disable row level security;