-- Criação da tabela de usuário (Estudante)
create table public.usuario (
  id bigint generated by default as identity primary key,
  uid uuid not null unique, -- Vínculo com Supabase Auth
  nome text,
  email text,
  senha text, -- Senha salva apenas para fins didáticos
  tempo_de_estudo bigint default 0, -- Em minutos (int8)
  tempo_de_exercicio bigint default 0 -- Em minutos (int8)
);

-- Configuração de segurança (RLS desativado para estudo)
alter table public.usuario disable row level security;