-- 1. TABELA EXERCÍCIO (Catálogo de alongamentos)
-- Não tem usuario_id pois são exercícios padrão do sistema
create table public.exercicio (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  url_video text,
  duracao_seg int8 not null default 0
);

-- 2. TABELA META DIÁRIA (Goals)
create table public.meta_diaria (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null, -- Vínculo com o aluno
  data text not null, -- Formato ISO (2025-12-08)
  meta_minutos int8 not null default 0,
  minutos_atuais int8 not null default 0,
  concluido boolean default false
);

-- 3. TABELA CONQUISTA (Gamification)
create table public.conquista (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null, -- Vínculo com o aluno
  titulo text not null,
  descricao text,
  nome_icone text,
  desbloqueada boolean default false,
  desbloqueada_em text -- Data ISO (pode ser nulo)
);

-- 4. TABELA HIDRATAÇÃO (Saúde)
create table public.hidratacao (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null, -- Vínculo com o aluno
  data_registro text not null, -- Data ISO
  ml_consumidos int8 not null default 0,
  meta_diaria_ml int8 not null default 2000
);

-- DESATIVAR SEGURANÇA (RLS) PARA TESTES
alter table public.exercicio disable row level security;
alter table public.meta_diaria disable row level security;
alter table public.conquista disable row level security;
alter table public.hidratacao disable row level security;